name: Astro CI

on: pull_request

jobs:
  build_and_ci:
    name: Build and ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        run: docker build -t pandoc-astro-builder .

      - name: Astro & Pandoc Build
        run: docker run --rm -it -w /io -v ${pwd}:/io pandoc-astro-builder bash -c "npm ci && npm run build"
